
version: "3"

volumes:

  my-django-data:

services:
  web:
    build:
      context: .
      dockerfile: django/Dockerfile
    
    volumes:
    - my-django-data:/media

    working_dir: "/code"
    
    # the port mapping
    ports:
    - "9000:8000"

